routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => 'auth', 'prefix' => 'home'], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('stuff', 'StuffController')->except(['create', 'show', 'edit']);
    Route::resource('stock', 'StockController')->except(['create', 'show', 'edit']);
    Route::resource('transaction', 'TransactionController');
    Route::post('transaction/item', 'TransactionController@storeTrxItem')->name('transaction.item.store');
    Route::delete('transaction/item/delete/{id}', 'TransactionController@deleteTrxItem')->name('transaction.item.destroy');
    Route::get('transaction/verify/{id}', 'TransactionController@doVerified')->name('transaction.verify');
});

app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Haruncpi\LaravelIdGenerator\IdGenerator;
use Validator;
use DB;
use Alert;

class TransactionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $data = DB::table('transactions')->orderBy('id', 'asc')->get();
        return view('transaction.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $valid = Validator::make($request->all(), [
            'name' => 'required',
            'phone' => 'required',
            'address' => 'required',
            'type' => 'required'
        ]);
        if ($valid->fails()) {
            Alert::info('Info', $valid->errors()->first());
            return redirect()->back();
        } else {
            $post = DB::transaction(function () use ($request) {
                try {
                    DB::table('transactions')->insert([
                        'code' => IdGenerator::generate(['table' => 'transactions', 'field' => 'code', 'length' => 10, 'prefix' =>'TRX-']),
                        'name' => $request->name,
                        'phone' => $request->phone,
                        'address' => $request->address,
                        'type' => $request->type,
                        'total' => 0,
                        'description' => $request->description,
                        'created_at' => date('Y-m-d H:i:s')
                    ]);
                    $lastId = DB::getPdo()->lastInsertId();
                    Alert::success('Berhasil', 'Transaksi Berhasil Dibuat');
                    return redirect('home/transaction/' . base64_encode($lastId));
                } catch (\Exception $e) {
                    DB::rollback();
                    Alert::error('Error', $e->getMessage());
                    return redirect()->back();
                } 
            });
            return $post;
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $data = DB::table('transactions')->where('id', base64_decode($id))->first();
        $item = DB::table('transaction_items as a')
                    ->select('a.*', 'b.name', 'b.code as stuffCode')
                    ->leftJoin('stuffs as b', 'a.stuff_id', 'b.id')
                    ->where('a.transaction_id', base64_decode($id))
                    ->get();
        $stuff = DB::table('stocks as a')
                    ->select('a.*', 'b.name', 'b.code')
                    ->leftJoin('stuffs as b', 'a.stuff_id', 'b.id')
                    ->where('a.status', 'in')
                    ->orderBy('b.name', 'asc')
                    ->get();
        return view('transaction.show', compact('data', 'item', 'stuff'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $valid = Validator::make($request->all(), [
            'name' => 'required',
            'phone' => 'required',
            'address' => 'required',
            'type' => 'required'
        ]);
        if ($valid->fails()) {
            Alert::info('Info', $valid->errors()->first());
            return redirect()->back();
        } else {
            $post = DB::transaction(function () use ($request, $id) {
                try {
                    DB::table('transactions')->where('id', base64_decode($id))->update([
                        'name' => $request->name,
                        'phone' => $request->phone,
                        'address' => $request->address,
                        'type' => $request->type,
                        'description' => $request->description
                    ]);
                    Alert::success('Berhasil', 'Transaksi Berhasil Diupdate');
                    return redirect()->back();
                } catch (\Exception $e) {
                    DB::rollback();
                    Alert::error('Error', $e->getMessage());
                    return redirect()->back();
                } 
            });
            return $post;
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $del = DB::table('transactions')->where('id', base64_decode($id))->delete();
        if ($del) {
            Alert::success('Berhasil', 'Transaksi Berhasil Dihapus');
            return redirect()->back();
        } else {
            Alert::error('Error', 'Transaksi Gagal Dihapus');
            return redirect()->back();
        }
    }

    public function storeTrxItem(Request $request)
    {
        $valid = Validator::make($request->all(), [
            'trx' => 'required',
            'stuff' => 'required',
            'qty' => 'required',
            'price' => 'required'
        ]);
        if ($valid->fails()) {
            Alert::info('Info', $valid->errors()->first());
            return redirect()->back();
        } else {
            $post = DB::transaction(function () use ($request) {
                try {
                    $check = DB::table('transaction_items')->where('transaction_id', $request->trx)->where('stuff_id', $request->stuff)->count();
                    if ($check >= 1) {
                        $data = DB::table('transaction_items')->where('transaction_id', $request->trx)->where('stuff_id', $request->stuff)->first();
                        DB::table('transaction_items')->where('id', $data->id)->update([
                            'qty' => $request->qty,
                            'price' => $request->price,
                            'total' => $request->qty * $request->price
                        ]);
                        DB::table('stocks')->where('stuff_id', $request->stuff)->where('status', 'in')->decrement('total', $request->qty);
                        Alert::success('Berhasil', 'Barang Berhasil Ditambahkan');
                        return redirect()->back();
                    } else {
                        DB::table('transaction_items')->insert([
                            'transaction_id' => $request->trx,
                            'stuff_id' => $request->stuff,
                            'qty' => $request->qty,
                            'price' => $request->price,
                            'total' => $request->qty * $request->price
                        ]);
                        DB::table('stocks')->where('stuff_id', $request->stuff)->where('status', 'in')->decrement('total', $request->qty);
                        Alert::success('Berhasil', 'Barang Berhasil Ditambahkan');
                        return redirect()->back();
                    }
                } catch (\Exception $e) {
                    DB::rollback();
                    Alert::error('Error', $e->getMessage());
                    return redirect()->back();
                }
            });
            return $post;
        }
    }

    public function deleteTrxItem($id)
    {
        $data = DB::table('transaction_items')->where('id', base64_decode($id))->first();
        DB::table('stocks')->where('stuff_id', $data->stuff_id)->where('status', 'in')->increment('total', $data->qty);
        $del = DB::table('transaction_items')->where('id', base64_decode($id))->delete();
        if ($del) {
            Alert::success('Berhasil', 'Barang Berhasil Dihapus');
            return redirect()->back();
        } else {
            Alert::error('Error', 'Gagal Menghapus Barang');
            return redirect()->back();
        }
    }

    public function doVerified($id)
    {
        $total = DB::table('transaction_items')->where('transaction_id', base64_decode($id))->sum('total');
        $data = DB::table('transactions')->where('id', base64_decode($id))->update([
            'isLocked' => true,
            'total' => $total
        ]);
        if ($data) {
            Alert::success('Berhasil', 'Berhasil Verifikasi Transaksi');
            return redirect()->back();
        } else {
            Alert::error('Error', 'Gagal Verifikasi Transaksi');
            return redirect()->back();
        }
    }
}

resources/views/transaction/index.blade.php
@extends('layouts.app')
@section('style')
<!-- DataTables -->
<link rel="stylesheet" href="{!! asset('plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') !!}">
<link rel="stylesheet" href="{!! asset('plugins/datatables-responsive/css/responsive.bootstrap4.min.css') !!}">
<link rel="stylesheet" href="{!! asset('plugins/datatables-buttons/css/buttons.bootstrap4.min.css') !!}">
<link rel="stylesheet" href="{!! asset('plugins/select2/css/select2.min.css') !!}">
@stop
@section('content')
<div class="card">
    <div class="card-header">
        <h3 class="card-title">List Transaksi</h3>
        <div class="card-tools">
            <button type="button" class="btn btn-sm btn-outline-primary btn-block" data-toggle="modal" data-target="#modal-primary">
                <i class="fa fa-plus"></i>
                Tambah Data
            </button>
        </div>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <table id="example1" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Kode</th>
                    <th>Deskripsi</th>
                    <th>Tipe</th>
                    <th>Total</th>
                    <th>Status</th>
                    <th>Dibuat Tanggal</th>
                    <th>Aksi</th>
                </tr>
            </thead>
            <tbody>
                @php $no = 1; @endphp
                @foreach($data as $row)
                <tr>
                    <td>{!! $no++ !!}</td>
                    <td>{!! $row->code !!}</td>
                    <td>{!! $row->description !!}</td>
                    <td align="center">
                        @if($row->type == 'sell')
                        <span class="badge bg-primary">Penjualan</span>
                        @else
                        <span class="badge bg-danger">Pembelian</span>
                        @endif
                    </td>
                    <td>Rp {!! number_format($row->total) !!}</td>
                    <td align="center">
                        @if($row->isLocked)
                        <span class="badge bg-success">Verified</span>
                        @else
                        <span class="badge bg-danger">Draft</span>
                        @endif
                    </td>
                    <td>{!! date('Y-m-d H:i:s', strtotime($row->created_at)) !!}</td>
                    <td align="center">
                        <div class="btn-group">
                            <a href="{!! route('transaction.show', base64_encode($row->id)) !!}" type="button" class="btn btn-warning">
                              <i class="fas fa-eye"></i>
                            </a>
                            @if(!$row->isLocked)
                            <a href="{!! route('transaction.verify', base64_encode($row->id)) !!}" type="button" class="btn btn-info">
                              <i class="fas fa-check"></i>
                            </a>
                            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#modDelete{!! $row->id !!}">
                              <i class="fas fa-trash"></i>
                            </button>
                            @endif
                        </div>
                    </td>
                </tr>

                <!-- /.card -->
                <div class="modal fade" id="modDelete{!! $row->id !!}">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title">Hapus Data</h4>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <p>Apakah kamu yakin akan menghapus data?</p>
                            </div>
                            <div class="modal-footer justify-content-between">
                                <button type="button" class="btn btn-outline-danger" data-dismiss="modal">Close</button>
                                <form method="POST" action="{!! route('transaction.destroy', base64_encode($row->id)) !!}">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-outline-primary">Submit</button>
                                </form>
                            </div>
                        </div>
                        <!-- /.modal-content -->
                    </div>
                    <!-- /.modal-dialog -->
                </div>
                <!-- /.modal -->
                @endforeach
            </tbody>
            <tfoot>
                <tr>
                    <th>No</th>
                    <th>Kode</th>
                    <th>Deskripsi</th>
                    <th>Tipe</th>
                    <th>Total</th>
                    <th>Status</th>
                    <th>Dibuat Tanggal</th>
                    <th>Aksi</th>
                </tr>
            </tfoot>
        </table>
    </div>
    <!-- /.card-body -->
    <!-- /.card -->
    <div class="modal fade" id="modal-primary">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Tambah Data</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <!-- form start -->
                    <form class="form-horizontal" method="POST" action="{!! route('transaction.store') !!}">
                        @csrf
                        <div class="card-body">
                        <div class="form-group row">
                            <label for="inputEmail3" class="col-sm-2 col-form-label">Nama</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="inputPassword3" name="name" placeholder="Masukkan Nama Pembeli">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="inputEmail3" class="col-sm-2 col-form-label">No. Telp</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="inputPassword3" name="phone" placeholder="Masukkan No. Telp Pembeli">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="inputEmail3" class="col-sm-2 col-form-label">Alamat</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="inputPassword3" name="address" placeholder="Masukkan Alamat Pembeli">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="inputEmail3" class="col-sm-2 col-form-label">Tipe</label>
                            <div class="col-sm-10">
                                <select class="form-control" name="type">
                                    <option value="-">Pilih Tipe</option>
                                    <option value="sell">Penjualan</option>
                                    <option value="buy">Pembelian</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="inputEmail3" class="col-sm-2 col-form-label">Catatan</label>
                            <div class="col-sm-10">
                                <textarea class="form-control" name="description" placeholder="Masukkan catatan">
                                    
                                </textarea>
                            </div>
                        </div>
                    </div>
                    <!-- /.card-body -->
                </div>
                <div class="modal-footer justify-content-between">
                    <button type="button" class="btn btn-outline-danger" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-outline-primary">Submit</button>
                </div>
                </form>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    <!-- /.modal -->
</div>
@stop
@section('script')
<!-- DataTables  & Plugins -->
<script src="{!! asset('plugins/datatables/jquery.dataTables.min.js') !!}"></script>
<script src="{!! asset('plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') !!}"></script>
<script src="{!! asset('plugins/datatables-responsive/js/dataTables.responsive.min.js') !!}"></script>
<script src="{!! asset('plugins/datatables-responsive/js/responsive.bootstrap4.min.js') !!}"></script>
<script src="{!! asset('plugins/datatables-buttons/js/dataTables.buttons.min.js') !!}"></script>
<script src="{!! asset('plugins/datatables-buttons/js/buttons.bootstrap4.min.js') !!}"></script>
<script src="{!! asset('plugins/jszip/jszip.min.js') !!}"></script>
<script src="{!! asset('plugins/pdfmake/pdfmake.min.js') !!}"></script>
<script src="{!! asset('plugins/pdfmake/vfs_fonts.js') !!}"></script>
<script src="{!! asset('plugins/datatables-buttons/js/buttons.html5.min.js') !!}"></script>
<script src="{!! asset('plugins/datatables-buttons/js/buttons.print.min.js') !!}"></script>
<script src="{!! asset('plugins/datatables-buttons/js/buttons.colVis.min.js') !!}"></script>
<script src="{!! asset('plugins/select2/js/select2.full.min.js') !!}"></script>
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script>
    $(function () {
        $("#example1").DataTable({
        "responsive": true, "lengthChange": false, "autoWidth": false,
        "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
        }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
        $('.select2').select2();
    });
</script>
@stop