routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => 'auth', 'prefix' => 'home'], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('stuff', 'StuffController')->except(['create', 'show', 'edit']);
    Route::resource('stock', 'StockController')->except(['create', 'show', 'edit']);
    Route::resource('transaction', 'TransactionController');
    Route::post('transaction/item', 'TransactionController@storeTrxItem')->name('transaction.item.store');
    Route::delete('transaction/item/delete/{id}', 'TransactionController@deleteTrxItem')->name('transaction.item.destroy');
    Route::get('transaction/verify/{id}', 'TransactionController@doVerified')->name('transaction.verify');
});

app/Http/Controllers/StockController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use Alert;
use Validator;

class StockController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $stuff = DB::table('stuffs')->orderBy('name', 'asc')->get();
        $data = DB::table('stocks as a')
                    ->select('a.*', 'b.name', 'b.code')
                    ->leftJoin('stuffs as b', 'a.stuff_id', 'b.id')
                    ->orderBy('id', 'asc')
                    ->get();
        return view('stock.index', compact('data', 'stuff'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $valid = Validator::make($request->all(), [
            'stuff' => 'required',
            'qty' => 'required',
            'status' => 'required'
        ]);
        if ($valid->fails()) {
            Alert::info('Info', $valid->errors()->first());
            return redirect()->back();
        } else {
            $post = DB::transaction(function () use ($request) {
                try {
                    $check = DB::table('stocks')->where('stuff_id', $request->stuff)->where('status', $request->status)->count();
                    if ($check >= 1) {
                        DB::table('stocks')->where('stuff_id', $request->stuff)->where('status', $request->status)->increment('total', $request->qty);
                        Alert::success('Berhasil', 'Stok Berhasil Ditambahkan');
                        return redirect()->back();
                    } else {
                        DB::table('stocks')->insert([
                            'stuff_id' => $request->stuff,
                            'total' => $request->qty,
                            'status' => $request->status,
                            'created_at' => date('Y-m-d H:i:s')
                        ]);
                        Alert::success('Berhasil', 'Stok Berhasil Dibuat');
                        return redirect()->back();
                    }
                } catch (\Exception $e) {
                    DB::rollback();
                    Alert::error('Terjadi Kesalahan', $e->getMessage());
                    return redirect()->back();
                }
            });
            return $post;
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $valid = Validator::make($request->all(), [
            'qty' => 'required'
        ]);
        if ($valid->fails()) {
            Alert::info('Info', $valid->errors()->first());
            return redirect()->back();
        } else {
            $post = DB::transaction(function () use ($request, $id) {
                try {
                    DB::table('stocks')->where('id', base64_decode($id))->update([
                        'total' => $request->qty,
                    ]);
                    Alert::success('Berhasil', 'Stok Berhasil Diupdate');
                    return redirect()->back();
                } catch (\Exception $e) {
                    DB::rollback();
                    Alert::error('Terjadi Kesalahan', $e->getMessage());
                    return redirect()->back();
                }
            });
            return $post;
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $del = DB::table('stocks')->where('id', base64_decode($id))->delete();
        if ($del) {
            Alert::success('Berhasil', 'Stok Barang Berhasil Dihapus');
            return redirect()->back();
        } else {
            Alert::error('Terjadi Kesalahan', 'Stok Barang Gagal Dihapus');
            return redirect()->back();
        }
    }
}

resources/views/stock/index.blade.php
@extends('layouts.app')
@section('style')
<!-- DataTables -->
<link rel="stylesheet" href="{!! asset('plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') !!}">
<link rel="stylesheet" href="{!! asset('plugins/datatables-responsive/css/responsive.bootstrap4.min.css') !!}">
<link rel="stylesheet" href="{!! asset('plugins/datatables-buttons/css/buttons.bootstrap4.min.css') !!}">
<link rel="stylesheet" href="{!! asset('plugins/select2/css/select2.min.css') !!}">
@stop
@section('content')
<div class="card">
    <div class="card-header">
        <h3 class="card-title">List Stok Barang</h3>
        <div class="card-tools">
            <button type="button" class="btn btn-sm btn-outline-primary btn-block" data-toggle="modal" data-target="#modal-primary">
                <i class="fa fa-plus"></i>
                Tambah Data
            </button>
        </div>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <table id="example1" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Nama Barang</th>
                    <th>Stok</th>
                    <th>Status</th>
                    <th>Dibuat Tanggal</th>
                    <th>Aksi</th>
                </tr>
            </thead>
            <tbody>
                @php $no = 1; @endphp
                @foreach($data as $row)
                <tr>
                    <td>{!! $no++ !!}</td>
                    <td>{!! $row->code !!} - {!! $row->name !!}</td>
                    <td>{!! number_format($row->total) !!}</td>
                    <td align="center">
                        @if($row->status == 'in')
                        <span class="badge bg-primary">In</span>
                        @else
                        <span class="badge bg-danger">Out</span>
                        @endif
                    </td>
                    <td>{!! date('d, F Y', strtotime($row->created_at)) !!}</td>
                    <td align="center">
                        <div class="btn-group">
                            <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#modUpdate{!! $row->id !!}">
                              <i class="fas fa-edit"></i>
                            </button>
                            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#modDelete{!! $row->id !!}">
                              <i class="fas fa-trash"></i>
                            </button>
                        </div>
                    </td>
                </tr>

                <!-- /.card -->
                <div class="modal fade" id="modUpdate{!! $row->id !!}">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title">Ubah Data Stok</h4>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <form class="form-horizontal" method="POST" action="{!! route('stock.update', base64_encode($row->id)) !!}">
                                    @csrf
                                    @method('PATCH')
                                    <div class="card-body">
                                    <div class="form-group row">
                                        <label for="inputPassword3" class="col-sm-2 col-form-label">Total</label>
                                        <div class="col-sm-10">
                                            <input type="number" class="form-control" id="inputPassword3" min="1" name="qty" value="{!! $row->total !!}">
                                        </div>
                                    </div>
                                </div>
                                <!-- /.card-body -->
                            </div>
                            <div class="modal-footer justify-content-between">
                                <button type="button" class="btn btn-outline-danger" data-dismiss="modal">Close</button>
                                <button type="submit" class="btn btn-outline-primary">Submit</button>
                            </div>
                            </form>
                        </div>
                        <!-- /.modal-content -->
                    </div>
                    <!-- /.modal-dialog -->
                </div>
                <!-- /.modal -->

                <!-- /.card -->
                <div class="modal fade" id="modDelete{!! $row->id !!}">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title">Hapus Data</h4>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <p>Apakah kamu yakin akan menghapus data?</p>
                            </div>
                            <div class="modal-footer justify-content-between">
                                <button type="button" class="btn btn-outline-danger" data-dismiss="modal">Close</button>
                                <form method="POST" action="{!! route('stock.destroy', base64_encode($row->id)) !!}">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-outline-primary">Submit</button>
                                </form>
                            </div>
                        </div>
                        <!-- /.modal-content -->
                    </div>
                    <!-- /.modal-dialog -->
                </div>
                <!-- /.modal -->
                @endforeach
            </tbody>
            <tfoot>
                <tr>
                    <th>No</th>
                    <th>Nama Barang</th>
                    <th>Stok</th>
                    <th>Status</th>
                    <th>Dibuat Tanggal</th>
                    <th>Aksi</th>
                </tr>
            </tfoot>
        </table>
    </div>
    <!-- /.card-body -->
    <!-- /.card -->
    <div class="modal fade" id="modal-primary">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Tambah Data Stok</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <!-- form start -->
                    <form class="form-horizontal" method="POST" action="{!! route('stock.store') !!}">
                        @csrf
                        <div class="card-body">
                        <div class="form-group row">
                            <label for="inputEmail3" class="col-sm-2 col-form-label">Barang</label>
                            <div class="col-sm-10">
                                <select class="form-control" style="width: 100%;" name="stuff">
                                    @foreach($stuff as $row)
                                    <option value="{!! $row->id !!}">{!! $row->name !!}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="inputPassword3" class="col-sm-2 col-form-label">Total</label>
                            <div class="col-sm-10">
                                <input type="number" class="form-control" id="inputPassword3" min="1" name="qty">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-form-label">Status</label>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="status" value="in">
                                <label class="form-check-label">In</label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="status" value="out">
                                <label class="form-check-label">Out</label>
                            </div>
                        </div>
                    </div>
                    <!-- /.card-body -->
                </div>
                <div class="modal-footer justify-content-between">
                    <button type="button" class="btn btn-outline-danger" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-outline-primary">Submit</button>
                </div>
                </form>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    <!-- /.modal -->
</div>
@stop
@section('script')
<!-- DataTables  & Plugins -->
<script src="{!! asset('plugins/datatables/jquery.dataTables.min.js') !!}"></script>
<script src="{!! asset('plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') !!}"></script>
<script src="{!! asset('plugins/datatables-responsive/js/dataTables.responsive.min.js') !!}"></script>
<script src="{!! asset('plugins/datatables-responsive/js/responsive.bootstrap4.min.js') !!}"></script>
<script src="{!! asset('plugins/datatables-buttons/js/dataTables.buttons.min.js') !!}"></script>
<script src="{!! asset('plugins/datatables-buttons/js/buttons.bootstrap4.min.js') !!}"></script>
<script src="{!! asset('plugins/jszip/jszip.min.js') !!}"></script>
<script src="{!! asset('plugins/pdfmake/pdfmake.min.js') !!}"></script>
<script src="{!! asset('plugins/pdfmake/vfs_fonts.js') !!}"></script>
<script src="{!! asset('plugins/datatables-buttons/js/buttons.html5.min.js') !!}"></script>
<script src="{!! asset('plugins/datatables-buttons/js/buttons.print.min.js') !!}"></script>
<script src="{!! asset('plugins/datatables-buttons/js/buttons.colVis.min.js') !!}"></script>
<script src="{!! asset('plugins/select2/js/select2.full.min.js') !!}"></script>
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script>
    $(function () {
        $("#example1").DataTable({
        "responsive": true, "lengthChange": false, "autoWidth": false,
        "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
        }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
    });
</script>
@stop